In [23]:
import pandas as pd
import numpy as np
import re

In [24]:
df = pd.read_excel('Apple.xlsx')

In [25]:
df.head()

,Product Name,Current Price,MRP,Discount,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL
0,"Apple iPhone 15 (Black, 128 GB)","₹59,400","₹59,900",NaN,4.6,"2,46,375 Ratings & 9,265 Reviews",NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,NaN,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...
1,"Apple iPhone 17 (White, 256 GB)","₹79,400","₹82,900",4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...
2,"Apple iPhone 17 (Black, 256 GB)","₹79,400","₹82,900",4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...
3,"Apple iPhone 17 (Sage, 256 GB)","₹79,400","₹82,900",4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...
4,"Apple iPhone 17e (Black, 256 GB)","₹62,900","₹64,900",3% off,4.6,222 Ratings & 21 Reviews,NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",NaN,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...

In [26]:
df['MRP'] = df['MRP'].str.replace('₹', '').str.replace(' ', '').str.replace(',', '').astype(float)
df['Current Price'] = df['Current Price'].str.replace('₹', '').str.replace(',', '').astype(float)

In [27]:
df.head()

,Product Name,Current Price,MRP,Discount,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL
0,"Apple iPhone 15 (Black, 128 GB)",59400.0,59900.0,NaN,4.6,"2,46,375 Ratings & 9,265 Reviews",NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,NaN,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...
1,"Apple iPhone 17 (White, 256 GB)",79400.0,82900.0,4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...
2,"Apple iPhone 17 (Black, 256 GB)",79400.0,82900.0,4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...
3,"Apple iPhone 17 (Sage, 256 GB)",79400.0,82900.0,4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...
4,"Apple iPhone 17e (Black, 256 GB)",62900.0,64900.0,3% off,4.6,222 Ratings & 21 Reviews,NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",NaN,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...

In [28]:
def extract_discount(value):
    if pd.isna(value):
        return 0  # or return None
    return int(value.replace('% off', ''))

df['Discount_Number'] = df['Discount'].apply(extract_discount)

In [29]:
df.head()

,Product Name,Current Price,MRP,Discount,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL,Discount_Number
0,"Apple iPhone 15 (Black, 128 GB)",59400.0,59900.0,NaN,4.6,"2,46,375 Ratings & 9,265 Reviews",NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,NaN,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...,0
1,"Apple iPhone 17 (White, 256 GB)",79400.0,82900.0,4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...,4
2,"Apple iPhone 17 (Black, 256 GB)",79400.0,82900.0,4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...,4
3,"Apple iPhone 17 (Sage, 256 GB)",79400.0,82900.0,4% off,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...,4
4,"Apple iPhone 17e (Black, 256 GB)",62900.0,64900.0,3% off,4.6,222 Ratings & 21 Reviews,NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",NaN,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...,3

In [30]:
df.drop("Discount", axis=1, inplace=True)

In [31]:
df.head()

,Product Name,Current Price,MRP,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL,Discount_Number
0,"Apple iPhone 15 (Black, 128 GB)",59400.0,59900.0,4.6,"2,46,375 Ratings & 9,265 Reviews",NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,NaN,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...,0
1,"Apple iPhone 17 (White, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...,4
2,"Apple iPhone 17 (Black, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...,4
3,"Apple iPhone 17 (Sage, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...,4
4,"Apple iPhone 17e (Black, 256 GB)",62900.0,64900.0,4.6,222 Ratings & 21 Reviews,NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",NaN,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...,3

In [32]:
brands = {
    'Apple': ['apple', 'iphone', 'ipad'],
    'motorola': ['motorola', 'moto'],
    'AI_plus': ['ai plus', 'aiplus'],
    'IQOO': ['iqoo'],
    'Tecno': ['tecno'],
    'lava': ['lava'],
    'readmi': ['readmi', 'redmi'],  
    'realme': ['realme'],
    'POCO': ['poco'],
    'nothing': ['nothing'],
    'Infix': ['infix'],
    'Oppo': ['oppo'],
    'vivo': ['vivo'],
    'Google': ['google', 'pixel'],
    'OnePlus': ['oneplus', 'one plus'],
    'Samsung': ['samsung', 'galaxy'],
}

def get_brand(product_name):
    if pd.isna(product_name):
        return 'Unknown'
    
    product_name = str(product_name).lower()
    
    for brand, keywords in brands.items():
        for keyword in keywords:
            if keyword in product_name:
                return brand
    return 'Unknown'
df['Brand'] = df['Product Name'].apply(get_brand)

In [33]:
df.head()

,Product Name,Current Price,MRP,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL,Discount_Number,Brand
0,"Apple iPhone 15 (Black, 128 GB)",59400.0,59900.0,4.6,"2,46,375 Ratings & 9,265 Reviews",NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,NaN,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...,0,Apple
1,"Apple iPhone 17 (White, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
2,"Apple iPhone 17 (Black, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
3,"Apple iPhone 17 (Sage, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",NaN,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
4,"Apple iPhone 17e (Black, 256 GB)",62900.0,64900.0,4.6,222 Ratings & 21 Reviews,NaN,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",NaN,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...,3,Apple

In [34]:
apple_avg_ram = 6  # Average iPhone RAM is 6GB
df.loc[df['Brand'] == 'Apple', 'RAM'] = apple_avg_ram

In [35]:
df.head()

,Product Name,Current Price,MRP,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL,Discount_Number,Brand
0,"Apple iPhone 15 (Black, 128 GB)",59400.0,59900.0,4.6,"2,46,375 Ratings & 9,265 Reviews",6.0,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,NaN,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...,0,Apple
1,"Apple iPhone 17 (White, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
2,"Apple iPhone 17 (Black, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
3,"Apple iPhone 17 (Sage, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,NaN,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
4,"Apple iPhone 17e (Black, 256 GB)",62900.0,64900.0,4.6,222 Ratings & 21 Reviews,6.0,NaN,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",NaN,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...,3,Apple

In [36]:
def extract_storage(product_name):
    if pd.isna(product_name):
        return None
    
    product_name = str(product_name)
    
    # Pattern: number followed by GB/TB (with optional space)
    patterns = [
        r'(\d+)\s*GB',      # Matches: 128GB, 128 GB
        r'(\d+)\s*TB',      # Matches: 1TB, 1 TB
        r'(\d+)\s*GB\s*ROM', # Matches: 128GB ROM
        r'(\d+)\s*GB\s*Storage', # Matches: 128GB Storage
    ]
    
    for pattern in patterns:
        match = re.search(pattern, product_name, re.IGNORECASE)
        if match:
            storage = int(match.group(1))
            # Convert TB to GB
            if 'TB' in pattern.upper():
                storage = storage * 1024
            return storage
    
    return None

In [37]:
df['Storage'] = df['Product Name'].apply(extract_storage)

In [38]:
df.head()

,Product Name,Current Price,MRP,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL,Discount_Number,Brand
0,"Apple iPhone 15 (Black, 128 GB)",59400.0,59900.0,4.6,"2,46,375 Ratings & 9,265 Reviews",6.0,128,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,NaN,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...,0,Apple
1,"Apple iPhone 17 (White, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
2,"Apple iPhone 17 (Black, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
3,"Apple iPhone 17 (Sage, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple
4,"Apple iPhone 17e (Black, 256 GB)",62900.0,64900.0,4.6,222 Ratings & 21 Reviews,6.0,256,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",NaN,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...,3,Apple

In [39]:
def extract_ratings_reviews(text):
    """
    Extract ratings and reviews from text
    Example: "2,46,375 Ratings & 9,265 Reviews"
    Returns: (ratings, reviews)
    """
    if pd.isna(text):
        return None, None
    
    text = str(text)
    
    # Extract ratings (numbers before 'Ratings')
    ratings_match = re.search(r'([\d,]+)\s*Ratings', text, re.IGNORECASE)
    ratings = ratings_match.group(1).replace(',', '') if ratings_match else None
    
    # Extract reviews (numbers before 'Reviews')
    reviews_match = re.search(r'([\d,]+)\s*Reviews', text, re.IGNORECASE)
    reviews = reviews_match.group(1).replace(',', '') if reviews_match else None
    
    return ratings, reviews

# Apply to dataframe
df[['Ratings', 'Reviews']] = df['Review text'].apply(
    lambda x: pd.Series(extract_ratings_reviews(x))
)

# Convert to numbers
df['Ratings'] = pd.to_numeric(df['Ratings'], errors='coerce')
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

In [40]:
df.head()

,Product Name,Current Price,MRP,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL,Discount_Number,Brand,Ratings,Reviews
0,"Apple iPhone 15 (Black, 128 GB)",59400.0,59900.0,4.6,"2,46,375 Ratings & 9,265 Reviews",6.0,128,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,NaN,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...,0,Apple,246375,9265
1,"Apple iPhone 17 (White, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple,15488,938
2,"Apple iPhone 17 (Black, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple,15488,938
3,"Apple iPhone 17 (Sage, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,NaN,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple,15488,938
4,"Apple iPhone 17e (Black, 256 GB)",62900.0,64900.0,4.6,222 Ratings & 21 Reviews,6.0,256,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",NaN,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...,3,Apple,222,21

In [41]:
battery_dict = {
    # iPhone 17 Series
    'iPhone 17 Pro Max (eSIM)': 5088,
    'iPhone 17 Pro (eSIM)': 4252,
    'iPhone 17 (eSIM)': 3692,
    'iPhone Air': 3149,
    
    # iPhone 16 Series
    'iPhone 16 Pro Max': 4685,
    'iPhone 16 Plus': 4674,
    'iPhone 16 Pro': 3582,
    'iPhone 16': 3561,
    
    # iPhone 15 Series
    'iPhone 15 Pro Max': 4422,
    'iPhone 15 Plus': 4383,
    'iPhone 15 Pro': 3274,
    'iPhone 15': 3349,
    
    # iPhone 14 Series
    'iPhone 14 Pro Max': 4323,
    'iPhone 14 Plus': 4325,
    'iPhone 14 Pro': 3200,
    'iPhone 14': 3279,
    
    # iPhone 13 Series
    'iPhone 13 Pro Max': 4352,
    'iPhone 13 Pro': 3095,
    'iPhone 13': 3227,
    'iPhone 13 mini': 2406,
    
    # iPhone 12 Series
    'iPhone 12 Pro Max': 3687,
    'iPhone 12 Pro': 2815,
    'iPhone 12': 2815,
    'iPhone 12 mini': 2227,
    
    # iPhone 11 Series
    'iPhone 11 Pro Max': 3969,
    'iPhone 11 Pro': 3046,
    'iPhone 11': 3110,
    
    # iPhone XS, XR, X Series
    'iPhone XS Max': 3174,
    'iPhone XS': 2658,
    'iPhone XR': 2942,
    'iPhone X': 2716,
    
    # iPhone 8 & 7 Series
    'iPhone 8 Plus': 2691,
    'iPhone 8': 1821,
    'iPhone 7 Plus': 2900,
    'iPhone 7': 1960,
    
    # iPhone 6 & SE Series
    'iPhone 6S Plus': 2750,
    'iPhone 6S': 1715,
    'iPhone 6 Plus': 2915,
    'iPhone 6': 1810,
    'iPhone SE (2022)': 2018,
    'iPhone SE (2020)': 1821,
    'iPhone SE (2016)': 1624,
    
    # Early Models
    'iPhone 5S': 1560,
    'iPhone 5C': 1510,
    'iPhone 5': 1440,
    'iPhone 4S': 1432,
    'iPhone 4': 1420,
    'iPhone 3GS': 1219,
    'iPhone 3G': 1150,
    'Original iPhone': 1400,
}

# Function to get battery capacity
def get_battery(product_name):
    if pd.isna(product_name):
        return None
    
    product_name = str(product_name)
    
    # Try exact match first
    for model, battery in battery_dict.items():
        if model in product_name:
            return battery
    
    # Try partial match
    for model, battery in battery_dict.items():
        # Extract key model name (e.g., "iPhone 15 Pro Max" from "iPhone 15 Pro Max 256GB")
        model_parts = model.split()
        if len(model_parts) >= 2:
            # Check if product contains the main model name
            main_model = ' '.join(model_parts[:2])  # e.g., "iPhone 15"
            if main_model in product_name:
                return battery
    
    return None

# Apply to dataframe
df['Battery'] = df['Product Name'].apply(get_battery)

# Fill remaining 0
df['Battery'] = df['Battery'].fillna(0)

In [42]:
df.head()

,Product Name,Current Price,MRP,Rating,Review text,RAM,Storage,Display,Camera,Battery,Processor,Product URL,Image URL,Discount_Number,Brand,Ratings,Reviews
0,"Apple iPhone 15 (Black, 128 GB)",59400.0,59900.0,4.6,"2,46,375 Ratings & 9,265 Reviews",6.0,128,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,3349.0,"A16 Bionic Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-15-black...,https://rukminim2.flixcart.com/image/312/312/x...,0,Apple,246375,9265
1,"Apple iPhone 17 (White, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,5088.0,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-white...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple,15488,938
2,"Apple iPhone 17 (Black, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,5088.0,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-black...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple,15488,938
3,"Apple iPhone 17 (Sage, 256 GB)",79400.0,82900.0,4.6,"15,488 Ratings & 938 Reviews",6.0,256,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,5088.0,"A19 Chip, 6 Core Processor Processor",https://www.flipkart.com/apple-iphone-17-sage-...,https://rukminim2.flixcart.com/image/312/312/x...,4,Apple,15488,938
4,"Apple iPhone 17e (Black, 256 GB)",62900.0,64900.0,4.6,222 Ratings & 21 Reviews,6.0,256,15.49 cm (6.1 inch) Super Retina XDR Display,"48MP Rear Camera | A19 chip, 6 Core",5088.0,NaN,https://www.flipkart.com/apple-iphone-17e-blac...,https://rukminim2.flixcart.com/image/312/312/x...,3,Apple,222,21

In [43]:
df.to_excel('Cleaned_Apple.xlsx', index=False)

In [44]:
df.isnull().sum()

Product Name         0
Current Price        0
MRP                407
Rating               0
Review text          0
RAM                  0
Storage              0
Display              0
Camera               0
Battery              0
Processor           94
Product URL          0
Image URL            0
Discount_Number      0
Brand                0
Ratings              0
Reviews              0
dtype: int64

In [45]:
df['MRP'] = np.where(
    (df['Discount_Number'] == 0) & (df['MRP'].isna() | (df['MRP'] == '')),
    df['Current Price'],
    df['MRP']
)

In [46]:
df.isnull().sum()

Product Name        0
Current Price       0
MRP                 0
Rating              0
Review text         0
RAM                 0
Storage             0
Display             0
Camera              0
Battery             0
Processor          94
Product URL         0
Image URL           0
Discount_Number     0
Brand               0
Ratings             0
Reviews             0
dtype: int64

In [47]:
# Extract model from Product Name and assign appropriate processor
def get_processor_from_model(product_name):
    if 'iPhone 17' in product_name:
        return 'A19 Chip, 6 Core Processor'
    elif 'iPhone 16' in product_name:
        return 'A18 Chip, 6 Core Processor'
    elif 'iPhone 15' in product_name:
        return 'A16 Bionic Chip, 6 Core Processor'
    elif 'iPhone 14' in product_name:
        return 'A15 Bionic Chip, 6 Core Processor'
    elif 'iPhone 13' in product_name:
        return 'A15 Bionic Chip Processor'
    elif 'iPhone 12' in product_name:
        return 'A14 Bionic Chip with Next Generation Neural Engine'
    elif 'iPhone 11' in product_name:
        return 'A13 Bionic Chip'
    elif 'iPhone X' in product_name or 'iPhone XS' in product_name:
        return 'A12 Bionic Chip'
    elif 'iPhone 8' in product_name:
        return 'A11 Bionic Chip'
    elif 'iPhone 7' in product_name:
        return 'A10 Fusion Chip'
    elif 'iPhone 6' in product_name or 'iPhone 6s' in product_name:
        return 'A9 Chip'
    elif 'iPhone SE' in product_name:
        # Check if 3rd gen
        if '3rd' in product_name:
            return 'A15 Bionic Chip, 6 Core Processor'
        else:
            return 'A13 Bionic Chip with 3rd Gen Neural Engine'
    else:
        return 'Unknown Processor'

# Apply to null rows only
df.loc[df['Processor'].isnull(), 'Processor'] = df.loc[df['Processor'].isnull(), 'Product Name'].apply(get_processor_from_model)

In [48]:
df.isnull().sum()

Product Name       0
Current Price      0
MRP                0
Rating             0
Review text        0
RAM                0
Storage            0
Display            0
Camera             0
Battery            0
Processor          0
Product URL        0
Image URL          0
Discount_Number    0
Brand              0
Ratings            0
Reviews            0
dtype: int64

In [49]:
df['Processor'] = df['Processor'].fillna('Unknown Processor')

In [50]:
df.to_excel('Cleaned_Apple.xlsx', index=False)